from foldrpp import Foldrpp
from foldrpp import split_data
import pandas as pd

# Define column names for the dataset


# Specify which columns are string attributes
str_attrs = [
    "top-left", "top-middle", "top-right",
    "middle-left", "middle-middle", "middle-right",
    "bottom-left", "bottom-middle", "bottom-right"
]
num_attrs = []  # No numeric attributes in this dataset
label, pos_val = "class", "positive"


model = Foldrpp(str_attrs, num_attrs, label, pos_val)
data = model.load_data('Data/tic-tac-toe.csv')




# Split the data into training and testing sets
data_train, data_test = split_data(data, ratio=0.8, rand=True)

# Fit the model on the training data
model.fit(data_train, ratio=0.8)



# Print ASP rules generated by the model
print("ASP Rules:")
print("-----------")
for r in model.asp():
    print(r)
    
# Example board state as a dict
board_dict = {
    "top-left": "x",
    "top-middle": "o",
    "top-right": "b",
    "middle-left": "b",
    "middle-middle": "x",
    "middle-right": "o",
    "bottom-left": "b",
    "bottom-middle": "b",
    "bottom-right": "x"
}

# Predict outcome for this board
prediction = model.predict(board_dict)
print(f"Foldrpp model prediction for board: {prediction}")

# To find best move, try all empty positions and pick the one with best prediction
def best_move_foldrpp(board_dict, player):
    best_val = None
    best_positions = []
    keys = list(board_dict.keys())
    for i, key in enumerate(keys):
        if board_dict[key] == "b":
            test_board = board_dict.copy()
            test_board[key] = player.lower()
            pred = model.predict(test_board)
            score = 1 if pred == "positive" else -1
            if best_val is None or score > best_val:
                best_val = score
                best_positions = [i]
            elif score == best_val:
                best_positions.append(i)
    return best_positions

positions = best_move_foldrpp(board_dict, "x")
if positions:
    print(f"Best move(s) for X (Foldrpp): {[pos+1 for pos in positions]} (1-9)")
else:
    print("No valid moves found by Foldrpp.")
